services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: event-processing-keycloak
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./infra/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    networks:
      - event-processing
    restart: unless-stopped

  kafka:
    image: apache/kafka:4.1.2
    container_name: event-processing-kafka
    ports:
      - "9092:9092"
    volumes:
      - ./infra/kafka/kafka_jaas.conf:/etc/kafka/kafka_jaas.conf:ro
    env_file:
      - .env
    networks:
      - event-processing
    restart: unless-stopped

  clickhouse:
    image: clickhouse:26.3
    container_name: event-processing-clickhouse
    ports:
      - "8123:8123"
    volumes:
      - ./infra/clickhouse/create_events_table.sql:/docker-entrypoint-initdb.d/create_events_table.sql:ro
    env_file:
      - .env
    networks:
      - event-processing
    restart: unless-stopped

networks:
  event-processing:
    name: event-processing
